# Generated by Django 4.2.1 on 2023-05-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RssFeedWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsdata',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
