# Generated by Django 4.2.1 on 2023-06-03 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RssFeedWeb', '0002_alter_subsdata_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
