# Generated by Django 4.2.1 on 2023-06-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RssFeedWeb', '0003_subsdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='scrapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField(unique=True)),
                ('main_title', models.CharField(max_length=100)),
            ],
        ),
    ]
